//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tamu.GeoInnovation.Geocoding.ExternalGeocoders.BingGeocodeService_V2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dev.virtualearth.net/webservices/v1/geocode/contracts", ConfigurationName="BingGeocodeService_V2.IGeocodeService")]
    public interface IGeocodeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc" +
            "ode", ReplyAction="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc" +
            "odeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Tamu.GeoInnovation.Geocoding.Core.BingGeocodeService_V2.ResponseSummary), Action="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc" +
            "odeResponseSummaryFault", Name="ResponseSummary", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
        Tamu.GeoInnovation.Geocoding.Core.BingGeocodeService_V2.GeocodeResponse Geocode(Tamu.GeoInnovation.Geocoding.Core.BingGeocodeService_V2.GeocodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve" +
            "rseGeocode", ReplyAction="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve" +
            "rseGeocodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Tamu.GeoInnovation.Geocoding.Core.BingGeocodeService_V2.ResponseSummary), Action="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve" +
            "rseGeocodeResponseSummaryFault", Name="ResponseSummary", Namespace="http://dev.virtualearth.net/webservices/v1/common")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tamu.GeoInnovation.Geocoding.Core.BingGeocodeService_V2.GeocodeLocation))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Tamu.GeoInnovation.Geocoding.Core.BingGeocodeService_V2.UserLocation))]
        Tamu.GeoInnovation.Geocoding.Core.BingGeocodeService_V2.GeocodeResponse ReverseGeocode(Tamu.GeoInnovation.Geocoding.Core.BingGeocodeService_V2.ReverseGeocodeRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGeocodeServiceChannel : Tamu.GeoInnovation.Geocoding.ExternalGeocoders.BingGeocodeService_V2.IGeocodeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeocodeServiceClient : System.ServiceModel.ClientBase<Tamu.GeoInnovation.Geocoding.ExternalGeocoders.BingGeocodeService_V2.IGeocodeService>, Tamu.GeoInnovation.Geocoding.ExternalGeocoders.BingGeocodeService_V2.IGeocodeService {
        
        public GeocodeServiceClient() {
        }
        
        public GeocodeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeocodeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeocodeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeocodeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Tamu.GeoInnovation.Geocoding.Core.BingGeocodeService_V2.GeocodeResponse Geocode(Tamu.GeoInnovation.Geocoding.Core.BingGeocodeService_V2.GeocodeRequest request) {
            return base.Channel.Geocode(request);
        }
        
        public Tamu.GeoInnovation.Geocoding.Core.BingGeocodeService_V2.GeocodeResponse ReverseGeocode(Tamu.GeoInnovation.Geocoding.Core.BingGeocodeService_V2.ReverseGeocodeRequest request) {
            return base.Channel.ReverseGeocode(request);
        }
    }
}
